### ISSUE TITLE
setup_cluster should check for an impersonate configuration

### ISSUE THREAD

**Issue by dazza-codes** [dpn-admin/dpn-server#38]
I get an error when running the `setup_cluster`, i.e.

``` sh
$ bundle exec ./script/setup_cluster.rb 
Setting up db that impersonates local aptrust node.
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/data/src/dlss/dpn/dpn-server/config/initializers/dpn.rb:10:in `block in <top (required)>'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
/data/src/dlss/dpn/dpn-server/.bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
/data/src/dlss/dpn/dpn-server/config/initializers/dpn.rb:9:in `<top (required)>'
```

The problem is that the `script/setup_cluster.rb` is using a `Rails.env == 'impersonate'`, i.e.
https://github.com/dpn-admin/dpn-server/blob/master/script/setup_cluster.rb#L18

That `Rails.env` does not exist in the default `config/dpn.yml` generated by `rake config` from `config/dpn.yml.example`.

**Comment by dazza-codes** [comment]
This is fixed in #44
